[ci] Colorize cpp diff output (#3383)
* [ci] Colorize cpp diff output
* [ci] Add clang-format rule for east const

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,6 +36,7 @@ jobs:
         sudo apt-get install -y software-properties-common cppcheck luajit-5.1-dev luarocks mariadb-server mariadb-client libmariadb-dev-compat binutils-dev
         pip install -r tools/requirements.txt
         luarocks install luacheck --local
+        npm install -g diff-so-fancy
     - id: changed-files
       name: Get Changed Files
       uses: Ana06/get-changed-files@v2.2.0
@@ -103,11 +104,17 @@ jobs:
             exit 1
           fi
         done
-        git diff >> cpp_formatting_checks.txt
-        cat cpp_formatting_checks.txt
+        git diff --color >> cpp_formatting_checks.txt
         git reset --hard
         if [ -s cpp_formatting_checks.txt ]
         then
+          echo ""
+          echo "You have errors in your C++ code formatting."
+          echo "Please see below in red for the incorrect formatting, and in green for the correct formatting."
+          echo "You can either fix the formatting by hand or use clang-format."
+          echo "(You can safely ignore warnings about \$TERM and tput)"
+          echo ""
+          cat cpp_formatting_checks.txt | diff-so-fancy || true
           exit 1
         fi
         exit 0
