fix(trusts): massive trust overhaul

diff --git a/.github/workflows/build_develop.yml b/.github/workflows/build_develop.yml
--- a/.github/workflows/build_develop.yml
+++ b/.github/workflows/build_develop.yml
@@ -1,4 +1,4 @@
-name: Develop Builds
+name: Develop Checks
 
 on:
   push:
@@ -10,63 +10,114 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
   cancel-in-progress: true
 
-env:
-  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
-
 jobs:
-  Docker_Build_ARM64:
-    name: Build (arm64)
+  Sanity_Checks:
+    name: Sanity Checks
     runs-on: ubuntu-latest
-    env:
-      REPO_OWNER: 'jasonpulse'
-      REPO: 'jasonpulse/xiserver'
+    container:
+      image: ${{ vars.DEVTOOLS_IMAGE || 'ghcr.io/landsandboat/devtools:ubuntu' }}
+    defaults:
+      run:
+        shell: bash
     steps:
-      - name: Lowercase repository owner
-        run: |
-          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
-          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
 
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 1
+          fetch-depth: 0
 
-      - uses: docker/setup-qemu-action@v3
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip setuptools wheel
+          python -m pip install --upgrade -r ./tools/requirements.txt
+
+      - name: Run checks
+        run: ./tools/ci/sanity_checks.sh HEAD~1
+
+      - name: Add sanity checks report to summary
+        if: ${{ always() }}
+        run: tr -d '\r' < sanity_checks_summary.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Upload changed files as artifact
+        uses: actions/upload-artifact@v4
         with:
-          platforms: arm64
+          name: changed-files
+          path: changed-files.txt
+        continue-on-error: true
 
-      - uses: docker/setup-buildx-action@v3
-
-      - uses: docker/login-action@v3
+  Lua_Language_Server:
+    name: Lua Language Server
+    needs: Sanity_Checks
+    runs-on: ubuntu-latest
+    container:
+      image: ${{ vars.DEVTOOLS_IMAGE || 'ghcr.io/landsandboat/devtools:ubuntu' }}
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Download Changed Files
+        uses: actions/download-artifact@v4
         with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          name: changed-files
 
-      - name: Docker meta
-        id: docker-meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ghcr.io/${{ env.REPO }}
-          tags: |
-            type=raw,value=develop
-            type=sha
-          labels: |
-            org.opencontainers.image.title=Xi Server Develop (arm64)
+      - name: Check For Changed Lua Files
+        id: check-changes
+        run: |
+          mapfile -t changed_files < changed-files.txt
+          lua_changes=false
+          for changed_file in ${changed_files[@]}; do
+              if [[ $changed_file == scripts/**/*.lua || $changed_file == modules/**/*.lua ]]; then
+                lua_changes=true
+                break
+              fi
+          done
+          echo "lua_changes=$lua_changes" >> $GITHUB_OUTPUT
 
-      - name: Build and push
-        uses: docker/build-push-action@v6
+      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
+
+      - uses: actions/checkout@v4
+        if: ${{ steps.check-changes.outputs.lua_changes == 'true' }}
         with:
-          context: .
-          file: ./docker/ubuntu-arm64.Dockerfile
-          platforms: linux/arm64
-          push: true
-          tags: ${{ steps.docker-meta.outputs.tags }}
-          labels: ${{ steps.docker-meta.outputs.labels }}
-          build-args: |
-            COMPILER=gcc
-            GCC_VERSION=14
-            CMAKE_BUILD_TYPE=Release
-            TRACY_ENABLE=OFF
-            PCH_ENABLE=ON
-            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git
-            COMMIT_SHA=${{ github.sha }}
+          fetch-depth: 0
+
+      - name: Install Python dependencies
+        if: ${{ steps.check-changes.outputs.lua_changes == 'true' }}
+        run: |
+          python -m pip install --upgrade pip setuptools wheel
+          python -m pip install --upgrade -r ./tools/requirements.txt
+
+      - name: Run Lua Language Server
+        id: run_lls
+        if: ${{ steps.check-changes.outputs.lua_changes == 'true' }}
+        run: python ./tools/ci/lua_lang_server.py
+
+      - name: Summarize run
+        id: summarize_run
+        if: ${{ steps.check-changes.outputs.lua_changes == 'true' }}
+        run: |
+          found_issues=false
+          check_file=lua_lang_errors.txt
+          if [[ -f "$check_file" && -s "$check_file" ]]; then
+              found_issues=true
+              echo "## :x: Run Failed" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+              tr -d '\r' < "$check_file" >> $GITHUB_STEP_SUMMARY
+              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+              echo "" >> $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "$found_issues" == "false" ]]; then
+              if [[ "${{ steps.run_lls.outcome }}" == "success" ]]; then
+                  echo "## :heavy_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
+              else
+                  echo "## :x: Lua Language Server had errors, but no specific output was found." >> $GITHUB_STEP_SUMMARY
+                  echo "Check the logs step for details." >> $GITHUB_STEP_SUMMARY
+                  found_issues=true
+              fi
+          fi
+          echo "issues_found=$found_issues" >> $GITHUB_OUTPUT
+
+      - name: Fail Workflow if Checks Failed
+        if: ${{ steps.check-changes.outputs.lua_changes == 'true' && (steps.run_lls.outcome == 'failure' || steps.summarize_run.outputs.issues_found == 'true') }}
+        run: |
+          echo "Lua Language Server failed. See summary for details."
+          exit 1
